class CatalogItem {
  final int id;
  final String name;
  final double rate;
  final String? category;

  const CatalogItem({
    required this.id,
    required this.name,
    required this.rate,
    this.category,
  });
}

class ItemCatalog {
  static const List<CatalogItem> items = [
    CatalogItem(id: 1, name: 'Paper bag', rate: 90),
    CatalogItem(id: 2, name: 'Pouch', rate: 75),
    CatalogItem(id: 3, name: 'Roll', rate: 230),
    CatalogItem(id: 4, name: 'Ghasni', rate: 75),
    CatalogItem(id: 5, name: 'Sponge', rate: 75),
    CatalogItem(id: 6, name: 'Kanda-limbu bag', rate: 150),
    CatalogItem(id: 7, name: 'Cap', rate: 60),
    CatalogItem(id: 8, name: 'Garbage bag big', rate: 110),
    CatalogItem(id: 9, name: 'Garbage bag green', rate: 150),
    CatalogItem(id: 10, name: 'Handle bag', rate: 135),
    CatalogItem(id: 11, name: 'White phenyl', rate: 180),
    CatalogItem(id: 12, name: 'Glass cleaner', rate: 220),
    CatalogItem(id: 13, name: 'Straw', rate: 25),
    CatalogItem(id: 14, name: 'Clean foil', rate: 350),
    CatalogItem(id: 15, name: 'Chutney box', rate: 96),
    CatalogItem(id: 16, name: 'Table Duster', rate: 160),
    CatalogItem(id: 17, name: 'Tissue box', rate: 510),
    CatalogItem(id: 18, name: 'Pav-Bhaji Container', rate: 360),
    CatalogItem(id: 19, name: 'Glass', rate: 60),
    CatalogItem(id: 20, name: 'Fluid gel', rate: 490),
    CatalogItem(id: 21, name: 'Scotch brite', rate: 35),
    CatalogItem(id: 22, name: 'Hand Wash', rate: 240),
    CatalogItem(id: 23, name: 'Water Glass', rate: 60),
    CatalogItem(id: 24, name: 'Biryani container', rate: 320),
    CatalogItem(id: 25, name: 'Caustic Soda', rate: 320),
    CatalogItem(id: 26, name: 'Juice glass', rate: 260),
    CatalogItem(id: 27, name: 'Zadu', rate: 80),
    CatalogItem(id: 28, name: 'Clean wrap', rate: 350),
    CatalogItem(id: 29, name: 'Garbage Bag black', rate: 110),
    CatalogItem(id: 30, name: 'Godrej liquid', rate: 300),
    CatalogItem(id: 31, name: 'Air freshener', rate: 590),
    CatalogItem(id: 32, name: 'Air freshener liquid', rate: 300),
    CatalogItem(id: 33, name: 'Arm guard', rate: 30),
    CatalogItem(id: 34, name: 'Nirma', rate: 62),
    CatalogItem(id: 35, name: 'Parcel bag', rate: 135),
    CatalogItem(id: 36, name: 'Indonesian Kharata', rate: 60),
    CatalogItem(id: 37, name: 'Supli', rate: 60),
    CatalogItem(id: 38, name: 'Box file', rate: 75),
    CatalogItem(id: 39, name: 'Pane bore', rate: 75),
    CatalogItem(id: 40, name: 'High ighter', rate: 25),
    CatalogItem(id: 41, name: 'Taps', rate: 260),
    CatalogItem(id: 42, name: 'Stier', rate: 15),
    CatalogItem(id: 43, name: 'Big container', rate: 6.4),
    CatalogItem(id: 44, name: 'Small container', rate: 4.4),
    CatalogItem(id: 45, name: 'Chain foil', rate: 330),
    CatalogItem(id: 46, name: 'Gloves', rate: 75),
    CatalogItem(id: 47, name: 'Napkin', rate: 96),
    CatalogItem(id: 48, name: 'Ladi duster', rate: 160),
    CatalogItem(id: 49, name: 'Toothpice', rate: 105),
    CatalogItem(id: 50, name: '750ml silver container', rate: 320),
    CatalogItem(id: 51, name: '450ml silver container', rate: 220),
    CatalogItem(id: 52, name: '600ml silver container', rate: 3.2),
    CatalogItem(id: 53, name: 'A4 rim', rate: 270),
    CatalogItem(id: 54, name: 'Garbage bag', rate: 30),
    CatalogItem(id: 55, name: 'Pop-up', rate: 500),
    CatalogItem(id: 56, name: 'Garbage bag small', rate: 30),
    CatalogItem(id: 57, name: 'Gloves oil chargs', rate: 30),
    CatalogItem(id: 58, name: 'Mop set', rate: 140),
    CatalogItem(id: 59, name: 'Wipper', rate: 170),
    CatalogItem(id: 60, name: 'Fan', rate: 260),
    CatalogItem(id: 61, name: 'White board marker black', rate: 25),
    CatalogItem(id: 62, name: 'Toilet roll', rate: 10),
    CatalogItem(id: 63, name: 'Sefty goggle', rate: 30),
    CatalogItem(id: 64, name: 'Phenyl', rate: 130),
    CatalogItem(id: 65, name: 'cleaning mug', rate: 230),
    CatalogItem(id: 66, name: 'Chuteniy bag', rate: 150),
    CatalogItem(id: 67, name: 'Mop', rate: 140),
    CatalogItem(id: 68, name: 'Air', rate: 1100),
    CatalogItem(id: 69, name: 'Oil', rate: 1200),
    CatalogItem(id: 70, name: '6x9 pouch', rate: 60),
    CatalogItem(id: 71, name: '300ml glass', rate: 60),
    CatalogItem(id: 72, name: 'Chai patti', rate: 330),
    CatalogItem(id: 73, name: 'Ice-Cream cup', rate: 50),
    CatalogItem(id: 74, name: 'Spoon', rate: 55),
    CatalogItem(id: 75, name: 'Wipper set', rate: 200),
    CatalogItem(id: 76, name: 'Pan item', rate: 150),
    CatalogItem(id: 77, name: 'Pencil dell small', rate: 180),
    CatalogItem(id: 78, name: 'Pencil calling', rate: 180),
    CatalogItem(id: 79, name: 'Gloves drawings', rate: 38),
    CatalogItem(id: 80, name: 'Garbage bag grey big', rate: 150),
    CatalogItem(id: 81, name: 'Garbage bag big black', rate: 110),
    CatalogItem(id: 82, name: 'Silicon gloves', rate: 30),
    CatalogItem(id: 83, name: 'Cotton gloves Heavy Duty', rate: 18),
    CatalogItem(id: 84, name: 'White board marker', rate: 280),
    CatalogItem(id: 85, name: '250ml plastic container', rate: 50),
    CatalogItem(id: 86, name: '500ml plastic container', rate: 80),
    CatalogItem(id: 87, name: '750ml plastic container', rate: 120),
    CatalogItem(id: 88, name: '1000ml plastic container', rate: 150),
    CatalogItem(id: 89, name: '6×11 silver pouch', rate: 400),
    CatalogItem(id: 90, name: '5×7 silver pouch', rate: 280),
    CatalogItem(id: 91, name: 'W cut parcel bags', rate: 70),
    CatalogItem(id: 92, name: '1/4 kirana bag', rate: 30),
    CatalogItem(id: 93, name: '1/2 kirana bag', rate: 50),
    CatalogItem(id: 94, name: '6 inch Sathe stick', rate: 15),
    CatalogItem(id: 95, name: '300ml Juice glass with lid', rate: 200),
    CatalogItem(id: 96, name: 'Bend straw', rate: 10),
    CatalogItem(id: 97, name: 'Umbrella straw', rate: 18),
    CatalogItem(id: 98, name: '200ml paper glass', rate: 40),
    CatalogItem(id: 99, name: '65ml tea glass', rate: 30),
    CatalogItem(id: 100, name: 'Paper plate', rate: 45),
    CatalogItem(id: 101, name: '500gm Rubber band packet', rate: 800),
    CatalogItem(id: 102, name: 'Tissue paper dispenser', rate: 2500),
    CatalogItem(id: 103, name: '9inch mop set', rate: 750),
    CatalogItem(id: 104, name: '18inch wipper', rate: 900),
    CatalogItem(id: 105, name: '24inch wipper', rate: 1200),
    CatalogItem(id: 106, name: '18inch hardy brush', rate: 600),
    CatalogItem(id: 107, name: 'Toilet brush', rate: 550),
    CatalogItem(id: 108, name: '5ltr bucket', rate: 900),
    CatalogItem(id: 109, name: '15ltr bucket', rate: 2000),
    CatalogItem(id: 110, name: 'Green pad scrubber', rate: 120),
    CatalogItem(id: 111, name: 'Steel scrubber', rate: 150),
    CatalogItem(id: 112, name: 'Checks duster', rate: 300),
    CatalogItem(id: 113, name: 'Yellow Sponge', rate: 270),
    CatalogItem(id: 114, name: 'Plastic supli', rate: 300),
    CatalogItem(id: 115, name: '24 inch Dry mop set', rate: 1050),
    CatalogItem(id: 116, name: 'Acid', rate: 750),
    CatalogItem(id: 117, name: 'Toilet cleaner liquid', rate: 900),
    CatalogItem(id: 118, name: 'Regular phenyl', rate: 600),
    CatalogItem(id: 119, name: 'Black phenyl', rate: 650),
    CatalogItem(id: 120, name: 'Compound phenyl', rate: 800),
    CatalogItem(id: 121, name: 'Air freshner liquid 5ltr', rate: 4500),
    CatalogItem(id: 122, name: 'Odonil air freshner', rate: 450),
    CatalogItem(id: 123, name: 'Godrej automatic air freshner machine with refill', rate: 3600),
    CatalogItem(id: 124, name: 'Scented Urinal screen', rate: 300),
    CatalogItem(id: 125, name: 'Scented dambar goli', rate: 240),
    CatalogItem(id: 126, name: 'Garbage bag 27×36', rate: 550),
    CatalogItem(id: 127, name: 'Garbage bag 19×21', rate: 360),
    CatalogItem(id: 128, name: 'Garbage bag 30×50', rate: 750),
    CatalogItem(id: 129, name: '72mtr silver foil', rate: 1200),
    CatalogItem(id: 130, name: '1kg silver foil', rate: 2700),
    CatalogItem(id: 131, name: 'Kitchen apron', rate: 1050),
    CatalogItem(id: 132, name: 'Kitchen cap', rate: 360),
    CatalogItem(id: 133, name: 'Skull cap', rate: 300),
  ];
}