// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdGRYjYM8M3PXu8p5b8hFgeFUMoUf9k-4',
    appId: '1:661974956527:web:a5d09e25c9fb3694f05e1a',
    messagingSenderId: '661974956527',
    projectId: 'invoiceflow-deafa',
    authDomain: 'invoiceflow-deafa.firebaseapp.com',
    storageBucket: 'invoiceflow-deafa.firebasestorage.app',
    measurementId: 'G-DL3W87NYBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ikztacfkFBWVNOJPlpnOA1i_LX4VuqM',
    appId: '1:661974956527:android:84431273bb457867f05e1a',
    messagingSenderId: '661974956527',
    projectId: 'invoiceflow-deafa',
    storageBucket: 'invoiceflow-deafa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbRDY-6Xiy2NWqZtZmjHUNUd7SVB7HDYs',
    appId: '1:661974956527:ios:56156f8378b9ad24f05e1a',
    messagingSenderId: '661974956527',
    projectId: 'invoiceflow-deafa',
    storageBucket: 'invoiceflow-deafa.firebasestorage.app',
    iosBundleId: 'com.invoiceflow.app.testProject',
  );
}
